import './markup.js';
import './switching-activity.js';
import './form.js';
import './map.js';
import './slider.js';
import './server.js';
import './filtering.js';
import './adding-pictures.js';
import './popup-message.js';
